# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "lint & unittest"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kivy_2_3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up a Kivy-runnable environment
      run: |
        sudo apt-get update
        sudo apt-get -y install xvfb pulseaudio xsel
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX
    - name: Install asynckivy and its dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest flake8 "kivy>=2.3,<2.4" "asyncgui>=0.8,<0.10"
        python -m pip install .
    - name: Lint with flake8
      run: make style
    - name: Test with pytest
      run: make test
