# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "lint & unittest"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  kivy_2_0_0:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup env
      run: |
        sudo apt-get update
        sudo apt-get -y install xvfb pulseaudio xsel
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest flake8 asyncgui kivy[base]==2.0.0
    - name: Lint with flake8
      run: make style
    - name: Test with pytest
      run: make test
